/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 2020/05/19 11:01:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */



























/* Drop Tables */

DROP TABLE IF EXISTS asset_elements CASCADE
;

DROP TABLE IF EXISTS asset_inventories CASCADE
;

DROP TABLE IF EXISTS asset_status CASCADE
;

DROP TABLE IF EXISTS event_list_asset CASCADE
;

DROP TABLE IF EXISTS event_list_bridge CASCADE
;

DROP TABLE IF EXISTS package_elements CASCADE
;

DROP TABLE IF EXISTS packages CASCADE
;

DROP TABLE IF EXISTS retrievelogs CASCADE
;

DROP TABLE IF EXISTS task_download_package CASCADE
;

DROP TABLE IF EXISTS task_download_package_assets CASCADE
;

DROP TABLE IF EXISTS task_install CASCADE
;

DROP TABLE IF EXISTS task_install_assets CASCADE
;

DROP TABLE IF EXISTS task_log CASCADE
;

DROP TABLE IF EXISTS task_log_assets CASCADE
;

DROP TABLE IF EXISTS task_log_retrievelogs CASCADE
;

DROP TABLE IF EXISTS task_reboot CASCADE
;

DROP TABLE IF EXISTS task_reboot_assets CASCADE
;

DROP TABLE IF EXISTS task_relation CASCADE
;

DROP TABLE IF EXISTS task_selftest CASCADE
;

DROP TABLE IF EXISTS task_selftest_assets CASCADE
;

/* Create Tables */

CREATE TABLE asset_elements
(
	asset_id text NOT NULL,
	type_id text NOT NULL,
	ip_address text NOT NULL   DEFAULT '',
	note text NOT NULL   DEFAULT '',
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE asset_inventories
(
	id serial NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	units json NOT NULL,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE asset_status
(
	id serial NOT NULL,
	type_id text NOT NULL,
	asset_id text NOT NULL,
	status text NOT NULL   DEFAULT 'Missing',
	error_code text NOT NULL   DEFAULT ''
)
;

CREATE TABLE event_list_asset
(
	id serial NOT NULL,
	type_id text NOT NULL   DEFAULT '',
	asset_id text NOT NULL   DEFAULT '',
	subject text NOT NULL   DEFAULT '',
	importance text NOT NULL   DEFAULT 'Information',
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE event_list_bridge
(
	id serial NOT NULL,
	type_id text NOT NULL   DEFAULT '',
	asset_id text NOT NULL   DEFAULT '',
	task_id integer NOT NULL,
	task_type text NOT NULL,
	subject text NOT NULL   DEFAULT '',
	importance text NOT NULL   DEFAULT 'Information',
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE package_elements
(
	id serial NOT NULL,
	package_id integer NOT NULL,
	key text NOT NULL,
	value text NOT NULL
)
;

CREATE TABLE packages
(
	id serial NOT NULL,
	package_id uuid NOT NULL,
	name text NOT NULL   DEFAULT '',
	status text NOT NULL   DEFAULT 'Uploading',
	comment text NOT NULL   DEFAULT '',
	upload_utc timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	upload_by text NOT NULL   DEFAULT '',
	summary text NOT NULL   DEFAULT '',
	description text NOT NULL   DEFAULT '',
	model text NOT NULL   DEFAULT '',
	memo text NOT NULL   DEFAULT '',
	bucket_name text NOT NULL   DEFAULT '',
	object_name text NOT NULL   DEFAULT '',
	ftp_file_path text NOT NULL   DEFAULT '',
	delete_flag boolean NOT NULL   DEFAULT false
)
;

CREATE TABLE retrievelogs
(
	id integer NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	status text NOT NULL,
	error_code text NOT NULL,
	error_msg text NOT NULL,
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_download_package
(
	id serial NOT NULL,
	task_id uuid NOT NULL,
	name text NOT NULL,
	package_id integer NOT NULL,
	status text NOT NULL,
	created_by text NOT NULL,
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_download_package_assets
(
	id integer NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	status text NOT NULL,	-- Complete, InProgress, Scheduled, SystemError, ConnectionError, DeviceError
	started_at timestamp(6) without time zone NULL,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_install
(
	id serial NOT NULL,
	task_id uuid NOT NULL,
	name text NOT NULL,
	package_id integer NOT NULL,
	status text NOT NULL,
	created_by text NOT NULL,
	created_at timestamp without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_install_assets
(
	id serial NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	status text NOT NULL,
	started_at timestamp without time zone NULL,
	updated_at timestamp without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_log
(
	id serial NOT NULL,
	task_id uuid NOT NULL,
	status text NOT NULL,
	log_type text NOT NULL,
	memo text NOT NULL   DEFAULT '',
	created_by text NOT NULL,
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_log_assets
(
	id integer NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	status text NOT NULL,
	started_at timestamp(6) without time zone NULL,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_log_retrievelogs
(
	id integer NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	ftp_file_path text NOT NULL   DEFAULT ''
)
;

CREATE TABLE task_reboot
(
	id serial NOT NULL,
	task_id uuid NOT NULL,
	status text NOT NULL,
	created_by text NOT NULL,
	memo text NOT NULL   DEFAULT '',
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_reboot_assets
(
	id integer NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	status text NOT NULL,
	started_at timestamp(6) without time zone NOT NULL,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_relation
(
	id serial NOT NULL,
	download_package_task_id integer NOT NULL,
	install_task_id integer NOT NULL
)
;

CREATE TABLE task_selftest
(
	id serial NOT NULL,
	task_id uuid NOT NULL,
	status text NOT NULL,
	created_by text NOT NULL,
	memo text NOT NULL   DEFAULT '',
	created_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE task_selftest_assets
(
	id integer NOT NULL,
	asset_id text NOT NULL,
	type_id text NOT NULL,
	status text NOT NULL,
	started_at timestamp(6) without time zone NOT NULL,
	updated_at timestamp(6) without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE asset_elements
  ADD CONSTRAINT "UNIQUE_asset_elements" UNIQUE (asset_id,type_id)
;

CREATE UNIQUE INDEX "IXFK_asset_elements_assets" ON asset_elements (asset_id ASC,type_id ASC)
;

ALTER TABLE asset_inventories ADD CONSTRAINT "PK_asset_inventories"
	PRIMARY KEY (id)
;

ALTER TABLE asset_inventories
  ADD CONSTRAINT "UNIQUE_asset_inventories" UNIQUE (asset_id,type_id)
;

CREATE UNIQUE INDEX "IXFK_asset_inventories_assets" ON asset_inventories (asset_id ASC,type_id ASC)
;

ALTER TABLE asset_status ADD CONSTRAINT "PK_asset_status"
	PRIMARY KEY (id)
;

ALTER TABLE asset_status
  ADD CONSTRAINT "UNIQUE_asset_status" UNIQUE (type_id,asset_id)
;

ALTER TABLE event_list_asset ADD CONSTRAINT "PK_event_list_asset"
	PRIMARY KEY (id)
;

ALTER TABLE event_list_bridge ADD CONSTRAINT "PK_event_list_bridge"
	PRIMARY KEY (id)
;

ALTER TABLE package_elements ADD CONSTRAINT "PK_package_elements"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_package_elements_packages" ON package_elements (package_id ASC)
;

ALTER TABLE packages ADD CONSTRAINT "PK_packages"
	PRIMARY KEY (id)
;

ALTER TABLE packages
  ADD CONSTRAINT "UNIQUE_packages" UNIQUE (package_id)
;

ALTER TABLE retrievelogs ADD CONSTRAINT "PK_retrievelogs"
	PRIMARY KEY (id,asset_id,type_id)
;

CREATE INDEX "IXFK_retrievelogs_task_log_retrievelogs" ON retrievelogs (id ASC,asset_id ASC,type_id ASC)
;

ALTER TABLE task_download_package ADD CONSTRAINT "PK_task_download_package"
	PRIMARY KEY (id)
;

ALTER TABLE task_download_package
  ADD CONSTRAINT "UNIQUE_task_download_package" UNIQUE (task_id)
;

CREATE INDEX "IXFK_task_download_package_packages" ON task_download_package (package_id ASC)
;

ALTER TABLE task_download_package_assets
  ADD CONSTRAINT "UNIQUE_task_download_package_assets" UNIQUE (id,asset_id,type_id)
;

CREATE INDEX "IXFK_task_download_package_assets_task_download_package" ON task_download_package_assets (id ASC)
;

ALTER TABLE task_install ADD CONSTRAINT "PK_task_install"
	PRIMARY KEY (id)
;

ALTER TABLE task_install
  ADD CONSTRAINT "UNIQUE_task_install" UNIQUE (task_id)
;

CREATE INDEX "IXFK_task_install_packages" ON task_install (package_id ASC)
;

ALTER TABLE task_install_assets
  ADD CONSTRAINT "UNIQUE_task_install_assets" UNIQUE (id,type_id,asset_id)
;

CREATE INDEX "IXFK_task_install_assets_task_install" ON task_install_assets (id ASC)
;

ALTER TABLE task_log ADD CONSTRAINT "PK_task_log"
	PRIMARY KEY (id)
;

ALTER TABLE task_log
  ADD CONSTRAINT "UNIQUE_task_log" UNIQUE (task_id)
;

ALTER TABLE task_log_assets
  ADD CONSTRAINT "UNIQUE_task_log_assets" UNIQUE (id,asset_id,type_id)
;

CREATE INDEX "IXFK_task_log_assets_task_log" ON task_log_assets (id ASC)
;

ALTER TABLE task_log_retrievelogs
  ADD CONSTRAINT "UNIQUE_task_log_retrievelogs" UNIQUE (id,asset_id,type_id)
;

CREATE INDEX "IXFK_task_log_retrievelogs_task_log" ON task_log_retrievelogs (id ASC)
;

ALTER TABLE task_reboot ADD CONSTRAINT "PK_task_reboot"
	PRIMARY KEY (id)
;

ALTER TABLE task_reboot
  ADD CONSTRAINT "UNIQUE_task_reboot" UNIQUE (task_id)
;

ALTER TABLE task_reboot_assets
  ADD CONSTRAINT "UNIQUE_task_reboot_assets" UNIQUE (asset_id,type_id)
;

CREATE INDEX "IXFK_task_reboot_assets_task_reboot" ON task_reboot_assets (id ASC)
;

ALTER TABLE task_relation ADD CONSTRAINT "PK_task_relation"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_task_relation_task" ON task_relation (download_package_task_id ASC)
;

CREATE INDEX "IXFK_task_relation_task_02" ON task_relation (install_task_id ASC)
;

CREATE INDEX "IXFK_task_relation_task_download_package" ON task_relation (download_package_task_id ASC)
;

CREATE INDEX "IXFK_task_relation_task_download_package_02" ON task_relation (download_package_task_id ASC)
;

CREATE INDEX "IXFK_task_relation_task_install" ON task_relation (install_task_id ASC)
;

CREATE INDEX "IXFK_task_relation_task_install_02" ON task_relation (install_task_id ASC)
;

ALTER TABLE task_selftest ADD CONSTRAINT "PK_task_selftest"
	PRIMARY KEY (id)
;

ALTER TABLE task_selftest
  ADD CONSTRAINT "UNIQUE_task_selftest" UNIQUE (task_id)
;

ALTER TABLE task_selftest_assets
  ADD CONSTRAINT "UNIQUE_task_selftest_assets" UNIQUE (asset_id,type_id)
;

CREATE INDEX "IXFK_task_selftest_assets_task_selftest" ON task_selftest_assets (id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE package_elements ADD CONSTRAINT "FK_package_elements_packages"
	FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE retrievelogs ADD CONSTRAINT "FK_retrievelogs_task_log_retrievelogs"
	FOREIGN KEY (id,asset_id,type_id) REFERENCES task_log_retrievelogs (id,asset_id,type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_download_package ADD CONSTRAINT "FK_task_download_package_packages"
	FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_download_package_assets ADD CONSTRAINT "FK_task_download_package_assets_task_download_package"
	FOREIGN KEY (id) REFERENCES task_download_package (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_install ADD CONSTRAINT "FK_task_install_packages"
	FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_install_assets ADD CONSTRAINT "FK_task_install_assets_task_install"
	FOREIGN KEY (id) REFERENCES task_install (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_log_assets ADD CONSTRAINT "FK_task_log_assets_task_log"
	FOREIGN KEY (id) REFERENCES task_log (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_log_retrievelogs ADD CONSTRAINT "FK_task_log_retrievelogs_task_log"
	FOREIGN KEY (id) REFERENCES task_log (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_reboot_assets ADD CONSTRAINT "FK_task_reboot_assets_task_reboot"
	FOREIGN KEY (id) REFERENCES task_reboot (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_relation ADD CONSTRAINT "FK_task_relation_task_download_package_02"
	FOREIGN KEY (download_package_task_id) REFERENCES task_download_package (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_relation ADD CONSTRAINT "FK_task_relation_task_install_02"
	FOREIGN KEY (install_task_id) REFERENCES task_install (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE task_selftest_assets ADD CONSTRAINT "FK_task_selftest_assets_task_selftest"
	FOREIGN KEY (id) REFERENCES task_selftest (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */















COMMENT ON COLUMN task_download_package_assets.status
	IS 'Complete, InProgress, Scheduled, SystemError, ConnectionError, DeviceError'
;









COMMENT ON TABLE task_relation
	IS '将来的に抽象的なtaskテーブルができたときには、テーブル構造を変える'
;




